#! /usr/bin/bash
# cleans up loose ends
#       Bold Colors #
 BBLACK='\033[1;30m'        # Black
   BRED='\033[1;31m'          # Red
 BGREEN='\033[1;32m'        # Green
BYELLOW='\033[1;33m'       # Yellow
 BWHITE='\033[1;37m'        # White
     NC='\033[0m'

BFWB='\e[1;30;107m'

if [ $(id -u) = 0 ];

then


printf "${BYELLOW}Setting windscribe helper service down and deleting logs that could leave traces of previous WS account.\n${NC}"

systemctl disable --now windscribe-helper.service
#systemctl stop windscribe-helper.service

declare -i i
for (( i = 0 ; i < 8 ; i++ )); do
#echo $i
(printf "++";sleep .1; printf "++"; sleep .1; printf "\b\b\b\b"; printf "<><><><>    "; sleep .1;);
done
wait $!

echo ' '
printf "\n${NC}\n
Complete
"
echo "- - - - - - - - "
systemctl status windscribe-helper.service | head

rm -rf /home/user/.local/Windscribe/Windscribe2/
rm -rf /home/user/.config/Windscribe/
rm -rf /var/log/windscribe

printf "\n\n"
echo "All done, service disabled and files removed."



else

printf "\n\n${BRED}\e[107mNOT RUNNING AS ROOT!!! Bye. \n\n${NC}"

fi


exit 0
