#! /usr/bin/bash

### colors

#       Reset
NC='\033[0m'              # Text Reset

#       Regular Colors #
BLACK='\033[0;30m'        # Black
RED='\033[0;31m'          # Red
GREEN='\033[0;32m'        # Green
YELLOW='\033[0;33m'       # Yellow
BLUE='\033[0;34m'         # Blue
WHITE='\033[0;37m'        # White

#       Bold Colors #
BBLACK='\033[1;30m'        # Black
BRED='\033[1;31m'          # Red
BGREEN='\033[1;32m'        # Green
BYELLOW='\033[1;33m'       # Yellow
BBLUE='\033[1;34m'         # Blue
BPURPLE='\033[1;35m'       # Purple
BCYAN='\033[1;36m'         # Cyan
BWHITE='\033[1;37m'        # White


## ## ## ## ## ## ## ##
 ## ## ## ## ## ## ## ##


ISROOT() {
if [ $UID = 0 ]
  then
    echo "Starting....";
    sleep .7
    clear
  else
    echo "UID is NOT 1001. Bye";
    exit 1;
  fi
}


##  ##  ##  ##  ##  ##  ##  ##  ##  ##  ###
## ##  ##  ##  ## ##  ##  ##  ##  ##  ## ##
##                                       ##
##   Functions			         ##
##                                       ##
## ##  ##  ##  ##  ##  ##  ##  ##  ##  # ##
##  ##  ##  ##  ##  ##  ##  ##  ##  ##  ###

INFO1() {

clear

(echo " " && echo -e "\e[1;31mMullvad Config Info: \e[1;0m" && mullvad relay get && echo " "     && mullvad tunnel get && echo " "    && mullvad lockdown-mode get && echo " "    &&  mullvad obfuscation get && echo " "   && mullvad dns get && echo " "  && echo -e "\e[1;31mCONNECTION STATUS: \e[1;0m" && mullvad status -v && echo " " && echo " ")


printf "\n${BGREEN}\n Exit with CTRL-C ${NC}\n\n"

printf "\e[1;94m"
bar=""
for ((i=0; i<25; i++)); do
 bar="${bar}|"
 sleep .2
 echo -ne "\r[${bar}]"
done



}

INFO2() {

clear

printf "\n\n${BWHITE}Devices\n\n${GREEN}"
ip -d -s link show wg0-mullvad

printf "\n\n\n${BYELLOW}--------------------------------------------------------------\n\n\n${NC}"

printf "${GREEN}"
ip -br address show wg0-mullvad
printf "${NC}\n\n"


printf "\n${BGREEN}\n Exit with CTRL-C ${NC}\n\n"

printf "\e[1;94m"
bar=""
for ((i=0; i<25; i++)); do
 bar="${bar}#"
 sleep .2
 echo -ne "\r[${bar}]"
done


}

##  ##  ##  ##  ##  ##  ##  ##  ##  ##  ###
## ##  ##  ##  ## ##  ##  ##  ##  ##  ## ##
##					 ##
##    Main Body of the script is below 	 ##
##					 ##
## ##  ##  ##  ##  ##  ##  ##  ##  ##  # ##
##  ##  ##  ##  ##  ##  ##  ##  ##  ##  ###


ISROOT
INFO1
INFO2

while true; do
INFO1
INFO2

done

