#!/bin/bash

# cleans up loose ends
#       Bold Colors #
 BBLACK='\033[1;30m'        # Black
   BRED='\033[1;31m'          # Red
 BGREEN='\033[1;32m'        # Green
BYELLOW='\033[1;33m'       # Yellow
 BWHITE='\033[1;37m'        # White
     NC='\033[0m'



printf "${BRED}Choose where to get current IP address info from. Enter a number to use that source. :\n"
printf "\n${BWHITE}1) am.i.mullvad.net\n2) ipinfo.io\n3) ipconfig.io\n4) ipify.org\n5) freeipapi.com - JSON Output\n6) ipapi.co\n7) ip-api.co\n\n"

CHOOSE()  {

echo -e "\e[0;37mEnter a number and press [ENTER]";
read -p "--> " CHOICE

if   [[ $CHOICE == "1" ]];
  then
	echo "am.i.mullvad.net has been selected"
        FULLREQ=https://am.i.mullvad.net/connected

elif [[ $CHOICE == "2" ]];
  then
	echo "ipinfo.io has been selected"
        FULLREQ=https://ipinfo.io

elif [[ $CHOICE == "3" ]];
  then
	echo "ipconfig.io has been selected"
        FULLREQ=https://api.ifconfig.me/

elif [[ $CHOICE == "4" ]];
  then
	echo "ipify.org has been selected"
        FULLREQ=https://api.ipify.org

elif [[ $CHOICE == "5" ]];
  then
	echo "freeapi.com has been selected"
        FULLREQ=https://free.freeipapi.com/api/json/

elif [[ $CHOICE == "6" ]];
  then
	echo "ipapi.co has been selected"
        FULLREQ=https://ipapi.co/json/

elif [[ $CHOICE == "7" ]];
  then
	echo "seeip.org has been selected"
        FULLREQ=https://api.seeip.org/geoip

elif [[ $CHOICE == "8" ]];
  then
	echo "ipapi.co has been selected"
        FULLREQ=https://webbrowsertools.com/ip-address/





 else
	echo "You must select a valid choice using a number corresponding to the desired URL"
	echo " "
        CHOOSE

 fi

}



REQ() {

printf "\n\n${BWHITE}========================================================"
printf "\nSending ip info request to $FULLREQ\n"
echo "========================================================"

printf "\e[1;33m\nWaiting for response from server\e[0;33m\n\n"
curl -s ${FULLREQ}

printf "${BWHITE}\n\n=============================================\n${NC}"

exit 0

}


REQJSON() {

printf "\n\n${BWHITE}========================================================"
printf "\nSending ip info request to $FULLREQ\n"
echo "========================================================"

printf "\e[1;33m\nWaiting for response from server\e[0;33m\n\n"
curl -s ${FULLREQ} | cat | jq


printf "${BWHITE}\n\n=============================================\n${NC}"

exit 0

}

CHOOSE
if [ $CHOICE ==  "5" ] || [ $CHOICE == "6" ] || [ $CHOICE == "7" ]   ];
  then
    REQJSON
  else
    REQ
fi


exit 0

