#!/bin/sh -e
# cleans up loose ends
#       Bold Colors #
 BBLACK='\033[1;30m'        # Black
   BRED='\033[1;31m'          # Red
 BGREEN='\033[1;32m'        # Green
BYELLOW='\033[1;33m'       # Yellow
 BWHITE='\033[1;37m'        # White
     NC='\033[0m'
 YELLOW='\033[0;33m'

# Creating space before script
echo " "

# Network manager Interface and connection info
#printf "${BWHITE}=============================================="

printf "\n Showing Network Devices and Connection Info\n\n\n"

#echo "=============================================="

echo "${NC}"
nmcli -p device

printf "\n${BYELLOW}\n\t-\t-\t-\t-\n\n${NC}"

echo '
Wireless'
iw dev | grep -e  phy -e Interface -e ifindex -e addr -e type -e txpower 
printf "\n${BYELLOW}\n\t-\t-\t-\t-\n\n${NC}"
echo "\n${BWHITE}Network Manager Info
-------------------------------------${NC}"

printf "${YELLOW}"
nmcli | grep -A 3 DNS
echo ' '
route
printf "\n${NC}"
ip -br a

echo ' '


echo "

"

exit 0

